from fastapi import FastAPI, HTTPException, status, Depends
from sqlalchemy.orm import Session
from models import Persona
from database import get_db
from schemas import PersonaCreate, PersonaResponse

app = FastAPI()

#Modificar una Persona
@app.put("/personas/{id}", response_model=PersonaResponse) #Usamos el esquema de PersonaResponse
def modificar_persona(id: int, datos_persona: PersonaCreate, db: Session=Depends(get_db)): #Usamos la plantilla PersonaCreate para los datos_persona
   #Guarda en variable "persona" una persona con el mismo id del db.
    persona = db.get(Persona, id)

    #Si no encuentra a la persona, entonces lanza error 404
    if not persona:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Persona no encontrada"
        )
    
    # Verificar si el DNI nuevo ya existe (si se est치 cambiando)
    if persona.dni != datos_persona.dni: #Si el anterior dni es distinto al nuevo, es decir, si se est치 cambiando
        existe_dni = db.query(Persona).filter(Persona.dni == datos_persona.dni).first() #busco el dni nuevo en la db
        if existe_dni: #Si existe en la db, lanzo la excepci칩n
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="El DNI ya est치 registrado"
            )
        
    #Actualizo los datos
    persona.nombre = datos_persona.nombre
    persona.email = datos_persona.email
    persona.dni = datos_persona.dni
    persona.telefono = datos_persona.telefono
    persona.fecha_nacimiento = datos_persona.fecha_nacimiento
    persona.esta_habilitado = datos_persona.esta_habilitado

    #Intento guardar los cambios
    try:
        db.commit()
        db.refresh(persona)
        return persona
    
    #Si ocurre un error inesperado, lanza error 500
    except Exception as e:
        db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Error Inesperado al actualizar persona"
        )